export const ALL_PLANTS = [
  "Ageratum",
  "Alder",
  "Alyssum",
  "American Holly",
  "Anchusa",
  "Angel's Trumpet",
  "Anise",
  "Asters",
  "Baby Blue Eyes",
  "Bachelor's Button",
  "Basket Flower",
  "Basswood",
  "Bee Balm",
  "Black Gum",
  "Black Locust",
  "Blackberries",
  "Blueberry",
  "Borage",
  "Buckeyes",
  "Buttercups",
  "Butterfly Bush",
  "Butterfly Weed",
  "Button Bush",
  "Calamintha ",
  "Calendula",
  "Calliopsis",
  "Candytuft",
  "Cantaloupe",
  "Cape Daisy",
  "Catalpa",
  "Catnip",
  "Chives",
  "Clary Sage",
  "Clematis",
  "Clover",
  "Coreopsis",
  "Coriander/Cilantro",
  "Cosmos",
  "Creeping Thyme",
  "Crocuses",
  "Cucumbers",
  "Dahlias",
  "Dame's Rocket",
  "Dandelions",
  "Eastern Redbud",
  "Echinacea",
  "English Ivy",
  "Fennel",
  "Foxglove",
  "Fruit Trees",
  "Gaillardia",
  "Gayfeather",
  "Geraniums",
  "Germander",
  "Globe Thistle",
  "Golden Rain Tree",
  "Goldenrod",
  "Gourds",
  "Hawthorns",
  "Hazels",
  "Helenium",
  "Hollyhocks",
  "Honeysuckle",
  "Honeywort",
  "Hosta",
  "Hyacinth",
  "Hyssop",
  "Indigo",
  "Lavender",
  "Lemon Balm",
  "Linden",
  "Magnolia",
  "Maples",
  "Marigolds",
  "Mints",
  "Money Plant",
  "Mountain Ash",
  "Nepeta",
  "Oregano",
  "Oriental Poppy",
  "Peppers",
  "Poplar",
  "Poppies",
  "Privet ",
  "Prunella",
  "Pumpkins",
  "Raspberries",
  "Rock Cress",
  "Rosemary",
  "Roses",
  "Sage",
  "Sea Holly",
  "Sedum",
  "Snowdrops",
  "Squash",
  "Squills",
  "Stock",
  "Strawberries",
  "Sunflower",
  "Sunflowers",
  "Sycamore",
  "Tansy",
  "Thyme",
  "Tulip",
  "Valerian",
  "Verbascum",
  "Veronica",
  "Watermelons",
  "Wild Garlic ",
  "Willows",
  "Yellow Hyssop",
  "Zinnias",
];
